version: "3.8"

services:
  web:
    build:
      context: ./til_221228
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./til_221228:/project
      - /project/node_modules
